package fr.medicapp.medicapp.model

import android.content.Context
import com.google.gson.annotations.SerializedName
import fr.medicapp.medicapp.database.converter.ModelToEntityMapper
import fr.medicapp.medicapp.database.entity.DoctorEntity

data class Doctor(
    var id: Long = 0L,
    @SerializedName("idNational") var nationalId: Int = 0,
    @SerializedName("idTypePP") var idTypePP: Int = 0,
    @SerializedName("idPP") var idPP: Int = 0,
    @SerializedName("codeCiviliteEx") var civilCodeEx: String = "",
    @SerializedName("libelleCiviliteEx") var civilLabelEx: String = "",
    @SerializedName("codeCivilite") var civilCode: String = "",
    @SerializedName("libelleCivilite") var civilLabel: String = "",
    @SerializedName("nom") var lastName: String = "",
    @SerializedName("prenom") var firstName: String = "",
    @SerializedName("codeProfession") var professionCode: String = "",
    @SerializedName("libelleProfession") var professionLabel: String = "",
    @SerializedName("codeCategorieProfessionnelle") var professionalCategoryCode: String = "",
    @SerializedName("libelleCategorieProfessionnelle") var professionalCategoryLabel: String = "",
    @SerializedName("codeTypeSavoirFaire") var skillTypeCode: String = "",
    @SerializedName("libelleTypeSavoirFaire") var skillTypeLabel: String = "",
    @SerializedName("codeSavoirFaire") var skillCode: String = "",
    @SerializedName("libelleSavoirFaire") var skillLabel: String = "",
    @SerializedName("codeModeExercice") var practiceModeCode: String = "",
    @SerializedName("libelleModeExercice") var practiceModeLabel: String = "",
    @SerializedName("numSiretSite") var siteSiretNumber: String = "",
    @SerializedName("numSirenSite") var siteSirenNumber: String = "",
    @SerializedName("numFinessSite") var siteFinessNumber: String = "",
    @SerializedName("numFinessEtabJuridique") var legalEstablishmentFinessNumber: String = "",
    @SerializedName("idTechStructure") var techStructureId: String = "",
    @SerializedName("raisonSocialeSite") var siteCompanyName: String = "",
    @SerializedName("enseigneCommercialeSite") var siteCommercialSign: String = "",
    @SerializedName("complementDestinataireCoordStructure") var structureRecipientComplement: String = "",
    @SerializedName("complementPointGeographiqueCoordStructure") var structureGeographicPointComplement: String = "",
    @SerializedName("numVoieCoordStructure") var structureStreetNumber: String = "",
    @SerializedName("indiceRepetitionVoieCoordStructure") var structureStreetRepeatIndex: String = "",
    @SerializedName("codeTypeVoieCoordStructure") var structureStreetTypeCode: String = "",
    @SerializedName("libelleTypeVoieCoordStructure") var structureStreetTypeLabel: String = "",
    @SerializedName("libelleVoieCoordStructure") var structureStreetLabel: String = "",
    @SerializedName("mentionDistributionCoordStructure") var structureDistributionMention: String = "",
    @SerializedName("bureauCedexCoordStructure") var structureCedexOffice: String = "",
    @SerializedName("codePostalCoordStructure") var structurePostalCode: String = "",
    @SerializedName("codeCommuneCoordStructure") var structureCommuneCode: String = "",
    @SerializedName("libelleCommuneCoordStructure") var structureCommuneLabel: String = "",
    @SerializedName("codePaysCoordStructure") var structureCountryCode: String = "",
    @SerializedName("libellePaysCoordStructure") var structureCountryLabel: String = "",
    @SerializedName("telephoneCoordStructure") var structurePhoneNumber: String = "",
    @SerializedName("telephone2CoordStructure") var structurePhoneNumber2: String = "",
    @SerializedName("telecopieCoordStructure") var structureFaxNumber: String = "",
    @SerializedName("adresseMailCoordStructure") var structureEmailAddress: String = "",
    @SerializedName("codeDepartementStructure") var structureDepartmentCode: String = "",
    @SerializedName("libelleDepartementStructure") var structureDepartmentLabel: String = "",
    @SerializedName("ancienIdStructure") var oldStructureId: String = "",
    @SerializedName("autoriteEnregistrement") var registrationAuthority: String = "",
    @SerializedName("codeSecteurActivite") var activitySectorCode: String = "",
    @SerializedName("libelleSecteurActivite") var activitySectorLabel: String = "",
    @SerializedName("codeSectionTableauPharmaciens") var pharmacistsTableSectionCode: String = "",
    @SerializedName("libelleSectionTableauPharmaciens") var pharmacistsTableSectionLabel: String = "",
    @SerializedName("codeRole") var roleCode: String = "",
    @SerializedName("libelleRole") var roleLabel: String = "",
    @SerializedName("codeGenreActivite") var activityGenreCode: String = "",
    @SerializedName("libelleGenreActivite") var activityGenreLabel: String = ""

) : ModelToEntityMapper<DoctorEntity> {
    override fun convert(context: Context): DoctorEntity {
        return DoctorEntity(
            id,
            nationalId,
            idTypePP,
            idPP,
            civilCodeEx,
            civilLabelEx,
            civilCode,
            civilLabel,
            lastName,
            firstName,
            professionCode,
            professionLabel,
            professionalCategoryCode,
            professionalCategoryLabel,
            skillTypeCode,
            skillTypeLabel,
            skillCode,
            skillLabel,
            practiceModeCode,
            practiceModeLabel,
            siteSiretNumber,
            siteSirenNumber,
            siteFinessNumber,
            legalEstablishmentFinessNumber,
            techStructureId,
            siteCompanyName,
            siteCommercialSign,
            structureRecipientComplement,
            structureGeographicPointComplement,
            structureStreetNumber,
            structureStreetRepeatIndex,
            structureStreetTypeCode,
            structureStreetTypeLabel,
            structureStreetLabel,
            structureDistributionMention,
            structureCedexOffice,
            structurePostalCode,
            structureCommuneCode,
            structureCommuneLabel,
            structureCountryCode,
            structureCountryLabel,
            structurePhoneNumber,
            structurePhoneNumber2,
            structureFaxNumber,
            structureEmailAddress,
            structureDepartmentCode,
            structureDepartmentLabel,
            oldStructureId,
            registrationAuthority,
            activitySectorCode,
            activitySectorLabel,
            pharmacistsTableSectionCode,
            pharmacistsTableSectionLabel,
            roleCode,
            roleLabel,
            activityGenreCode,
            activityGenreLabel
        )
    }
}
