name: Android CI

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  Nightly:
    name: '📦 Nightly'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    - name: Nightly
      uses: pyTooling/Actions/releaser@r0
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          app/build/outputs/apk/release/app-release-unsigned.apk
          app/build/outputs/apk/release/output-metadata.json
          LICENSE.md
